version: "2.4"

volumes:

  papasi:
    name: papasi
  database:
    name: papasi-database
services:
  
  papasi:
    container_name: papasi
    image: papasi/papasi-io:0.0.2
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: papasi.io
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: papasi.io
      LETSENCRYPT_EMAIL: admin@papasi.io
      ASPNETCORE_URLS: http://+:5000
      Logging__LogLevel__Default: Debug
    restart: unless-stopped
    #ports:
      #- "5000:5000"
    networks:
      - papasinetwork
      - proxy

  database:
    container_name: papasi-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    mem_limit: 2048m
    cpus: 0.500
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - papasi:/var/opt/mssql
    networks:
      - papasinetwork


networks:
  papasinetwork:
    external: false
    name: papasinetwork
  proxy:
    external: true
    name: proxy