version: "2.4"

services:
  
  papasi:
    container_name: papasi
    image: miladsoft/papasi:0.0.1
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: papasi.io
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: papasi.io
      LETSENCRYPT_EMAIL: admin@papasi.io
      ASPNETCORE_URLS: https://+:5000
      Logging__LogLevel__Default: Debug
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy