version: "2.4"

volumes:

  papasi:
    name: papasi
  database:
    name: papasi-database
services:
  
  papasi:
    container_name: papasi
    image: papasi/papasi-io:0.0.2
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: papasi.io
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: YOURDOMAIN
      LETSENCRYPT_EMAIL: admin@YOURDOMAIN.io
      ASPNETCORE_URLS: http://+:5000
      Logging__LogLevel__Default: Debug
      ConnectionStrings__DefaultConnection: "Server=database,1433;User Id=SA;Password=YOUR-PASSWORD;Encrypt=false"

    restart: unless-stopped
    depends_on:
       - database
    #ports:
      #- "5000:5000"
    networks:
      - papasinetwork
      - proxy

  database:
    container_name: papasi-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    mem_limit: 2048m
    cpus: 0.500
    environment:
      SA_PASSWORD: "YOUR-PASSWORD"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - database:/var/opt/mssql
    networks:
      - papasinetwork


networks:
  papasinetwork:
    external: false
    name: papasinetwork
  proxy:
    external: true
    name: proxy